### PR TITLE
Feat/import

### PR DESCRIPTION
**Pull request by andy9a9**
- implement import functionality
  - [x] Footprints
  - [x] Symbols
- switch to relative paths
- convert properties to dictionary
- check if input file is not empty

### CODE REVIEW

**Comment by andy9a9** [comment]
@EdizonTN Could you please test the import feature?
- Looks like, that the output is little bit different
  - make backup before testing ;)

**Review by EdizonTN — COMMENTED** [review]
SCH Symbols
- import one file is OK.
- import all files in directory is OK

PCB Footprint
- import one file: changed offset in 3D model!
- import all files from directory: changed offset in some of 3D model!
In all imported footprints was changed syntax in file, without any impact to footprint drawing. But Git to interpreted as change. :-(


Example of the 3D model move:  [PCB/Generic.pretty/DIP762W46P254L927H533Q8P_MS-001.kicad_mod](https://github.com/Z-Elektrik/LIB/blob/main/PCB/Generic.pretty/DIP762W46P254L927H533Q8P_MS-001.kicad_mod) - Compared by Git:
image

**Comment by andy9a9** [comment]
> PCB Footprint
> 
>     * import one file: changed offset in 3D model!
> 
>     * import all files from directory: changed offset in some of 3D model!
>       In all imported footprints was changed syntax in file, without any impact to footprint drawing. But Git to interpreted as change. :-(
> 
> 
> Example of the 3D model move: [PCB/Generic.pretty/DIP762W46P254L927H533Q8P_MS-001.kicad_mod](https://github.com/Z-Elektrik/LIB/blob/main/PCB/Generic.pretty/DIP762W46P254L927H533Q8P_MS-001.kicad_mod) - Compared by Git: image

Ok, I see the problem. `offset` is converted to `pos`, so we have to align with that.

**Review by EdizonTN — APPROVED** [review]
Perfect!
It' working now. 3D models are without move.
It's OK

**Pull request merged**
