### PR TITLE
refactor(kicad-from-to-csv)

### PR DESCRIPTION
**Pull request by andy9a9**
- refactor components handling
- add support for footprint(`.kicad_mod`)
- ⚠️ import not implemented

### CODE REVIEW

**Comment by EdizonTN** [comment]
Doesn't work with footprint library. 
Output:
`c:\Users\peter.janis\Documents\Workspace-KiCad\scripting\KiCad-to-csv-feat-footprint>python kicad-from-to-csv.py -a export c:\Users\peter.janis\Documents\Workspace-KiCad\LIB\PCB\Test.pretty PCBLIB7.csv
Processing...
Traceback (most recent call last):
  File "c:\Users\EdizonTN\Documents\Workspace-KiCad\scripting\KiCad-to-csv-feat-footprint\kicad-from-to-csv.py", line 231, in <module>
    comp.export() if action_type_export else comp.update()
    ^^^^^^^^^^^^^
  File "c:\Users\EdizonTN\Documents\Workspace-KiCad\scripting\KiCad-to-csv-feat-footprint\kicad-from-to-csv.py", line 110, in export
    self._sim_or_foot.FIXED_PROPERTIES
AttributeError: 'Footprints' object has no attribute 'FIXED_PROPERTIES'. Did you mean: 'CUSTOM_PROPERTIES'?`

**Comment by andy9a9** [comment]
> Doesn't work with footprint library. Output: `c:\Users\peter.janis\Documents\Workspace-KiCad\scripting\KiCad-to-csv-feat-footprint>python kicad-from-to-csv.py -a export c:\Users\peter.janis\Documents\Workspace-KiCad\LIB\PCB\Test.pretty PCBLIB7.csv

Ok, I see the problem. I was assuming, that files are in `.kicad_mod`, but they are in `.pretty`. Let me fix the assumtion.

**Comment by andy9a9** [comment]
> Doesn't work with footprint library. Output: `c:\Users\peter.janis\Documents\Workspace-KiCad\scripting\KiCad-to-csv-feat-footprint>python kicad-from-to-csv.py -a export c:\Users\peter.janis\Documents\Workspace-KiCad\LIB\PCB\Test.pretty PCBLIB7.csv Processing... Traceback (most recent call last): File "c:\Users\EdizonTN\Documents\Workspace-KiCad\scripting\KiCad-to-csv-feat-footprint\kicad-from-to-csv.py", line 231, in <module> comp.export() if action_type_export else comp.update() ^^^^^^^^^^^^^ File "c:\Users\EdizonTN\Documents\Workspace-KiCad\scripting\KiCad-to-csv-feat-footprint\kicad-from-to-csv.py", line 110, in export self._sim_or_foot.FIXED_PROPERTIES AttributeError: 'Footprints' object has no attribute 'FIXED_PROPERTIES'. Did you mean: 'CUSTOM_PROPERTIES'?`

Should be fixed now, please test it again.

**Review by EdizonTN — COMMENTED** [review]
Footprints was exported.
**But user fields not**. Example lib you can find in the attachment:
[Test.pretty.zip](https://github.com/user-attachments/files/15764504/Test.pretty.zip)
image

**Comment by andy9a9** [comment]
> Footprints was exported. **But user fields not**.

That's obvious, while I'm exporting just `description` and `models`, see https://github.com/Mikrozone-Server/KiCad-to-csv/blob/feat/footprint/kicad-from-to-csv.py#L49
Please write me the possible entries, which have to be exported.

**Comment by EdizonTN** [comment]
> > Footprints was exported. **But user fields not**.
> 
> That's obvious, while I'm exporting just `description` and `models`, see https://github.com/Mikrozone-Server/KiCad-to-csv/blob/feat/footprint/kicad-from-to-csv.py#L49 Please write me the possible entries, which have to be exported.

hmm, these fields are text object in the footprint not text properties as in the symbol. I wasn't become aware this.
If will be problem export these, forget about it.

Please try to add to export these fields:
- Keywords
- Fabrication Attributes: ComponentType
- Fabrication Attributes: NotInSchematic
- Fabrication Attributes: Exclude from position files
- Fabrication Attributes: Exclude from bill of materials
- Fabrication Attributes: Exempt from courtyard requirement

**Comment by andy9a9** [comment]
I've added there a `graphicItems` attribute to handle `fp_text`, but I guess the output is too long. So which fields do you require?

> Please try to add to export these fields:
>     * Keywords
>     * Fabrication Attributes: ComponentType
>     * Fabrication Attributes: NotInSchematic
>     * Fabrication Attributes: Exclude from position files
>     * Fabrication Attributes: Exclude from bill of materials
>     * Fabrication Attributes: Exempt from courtyard requirement

I can't find these information in `TestFootprint_Name.kicad_mod`, so where can I get them?

**Comment by EdizonTN** [comment]
> I've added there a `graphicItems` attribute to handle `fp_text`, but I guess the output is too long. So which fields do you require?
> 
> > Please try to add to export these fields:
> > * Keywords
> > * Fabrication Attributes: ComponentType
> > * Fabrication Attributes: NotInSchematic
> > * Fabrication Attributes: Exclude from position files
> > * Fabrication Attributes: Exclude from bill of materials
> > * Fabrication Attributes: Exempt from courtyard requirement
> 
> I can't find these information in `TestFootprint_Name.kicad_mod`, so where can I get them?

Uhh, Looks as bug in the KiCad v7. These information are not saved in to file.
image


In attachment you can find same file but in the ver.8. 
Properties are saved correctly. Use it.
[[Test.pretty8.zip](https://github.com/user-attachments/files/15774054/Test.pretty8.zip)]

**Comment by andy9a9** [comment]
> Uhh, Looks as bug in the KiCad v7. These information are not saved in to file. 

Maybe it's not a bug, but while the values are more-less booleans the v7 is storing them like an non-default values. So I would say we can store them like false, it they aren't defined.

On the other hand v8 is using them as a `properties`. I guess, we can't mix them up.

**Comment by EdizonTN** [comment]
> > Uhh, Looks as bug in the KiCad v7. These information are not saved in to file.
> 
> Maybe it's not a bug, but while the values are more-less booleans the v7 is storing them like an non-default values. So I would say we can store them like false, it they aren't defined.
> 
> On the other hand v8 is using them as a `properties`. I guess, we can't mix them up.

OK.

**Comment by andy9a9** [comment]
@EdizonTN Why did you close this PR?

**Comment by EdizonTN** [comment]
> @EdizonTN Why did you close this PR?

Ehm... I'm sorry. I clicked wrong button....

**Review by EdizonTN — CHANGES_REQUESTED** [review]
Fields "ki_description" and "ki_keywords" not correctly filled by values.
Example output: [SCHLIB7.csv](https://github.com/user-attachments/files/15799806/SCHLIB7.csv) where:
"ki_description" is filled with "RE" (RE is Reference)
"ki_keywords" is filled with "TestValue" (TestValue is Value)
And all next fields are filled with wrong values also (shifted by 2 values)

**Comment by andy9a9** [comment]
> Fields "ki_description" and "ki_keywords" not correctly filled by values. Example output: [SCHLIB7.csv](https://github.com/user-attachments/files/15799806/SCHLIB7.csv) where: "ki_description" is filled with "RE" (RE is Reference) "ki_keywords" is filled with "TestValue" (TestValue is Value) And all next fields are filled with wrong values also (shifted by 2 values)

I'm working on a generic solution. Btw, which input file did you use? The one from test folder?

**Comment by EdizonTN** [comment]
> > Fields "ki_description" and "ki_keywords" not correctly filled by values. Example output: [SCHLIB7.csv](https://github.com/user-attachments/files/15799806/SCHLIB7.csv) where: "ki_description" is filled with "RE" (RE is Reference) "ki_keywords" is filled with "TestValue" (TestValue is Value) And all next fields are filled with wrong values also (shifted by 2 values)
> 
> I'm working on a generic solution. Btw, which input file did you use? The one from test folder?

No. I create a new one: [Test7.zip](https://github.com/user-attachments/files/15802896/Test7.zip), but is similar as file from test folder...

**Comment by andy9a9** [comment]
Could you please check it again?

**Comment by andy9a9** [comment]
@EdizonTN  Could you please re-test it again?

>  image

For this one, there is a problem, that the `FpText` fields have the same values like `user`, `value`, ... . So there is no way to specify which entries have to be exported. On the other hand, are they relevant, or which values of the entry do you need?

**Review by EdizonTN — APPROVED** [review]

**Pull request merged**
